// This file is auto generated by icy-table.
#ifndef TABLE_COMPILER_INDEX
#define TABLE_COMPILER_INDEX
#define array_element_size(array) sizeof(array[0])
#define array_count(array) (sizeof(array)/array_element_size(array))
#include "icydb.h"
#include <stdlib.h>
#endif


alignments * alignments_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"id", (char *)"horizontal", (char *)"vertical"};
  static const char * const column_types[] = {"u64", "alignment", "alignment"};
  alignments * instance = calloc(sizeof(alignments), 1);
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  
  icy_table_init((icy_table * )instance, optional_name, 3, (unsigned int[]){sizeof(u64), sizeof(alignment), sizeof(alignment)}, (char *[]){(char *)"id", (char *)"horizontal", (char *)"vertical"});
  
  return instance;
}

void alignments_insert(alignments * table, u64 * id, alignment * horizontal, alignment * vertical, size_t count){
  void * array[] = {(void* )id, (void* )horizontal, (void* )vertical};
  icy_table_inserts((icy_table *) table, array, count);
}

void alignments_set(alignments * table, u64 id, alignment horizontal, alignment vertical){
  void * array[] = {(void* )&id, (void* )&horizontal, (void* )&vertical};
  icy_table_inserts((icy_table *) table, array, 1);
}

void alignments_lookup(alignments * table, u64 * keys, size_t * out_indexes, size_t count){
  icy_table_finds((icy_table *) table, keys, out_indexes, count);
}

void alignments_remove(alignments * table, u64 * keys, size_t key_count){
  size_t indexes[key_count];
  size_t index = 0;
  size_t cnt = 0;
  while(0 < (cnt = icy_table_iter((icy_table *) table, keys, key_count, NULL, indexes, array_count(indexes), &index))){
    icy_table_remove_indexes((icy_table *) table, indexes, cnt);
    index = 0;
  }
}

void alignments_clear(alignments * table){
  icy_table_clear((icy_table *) table);
}

void alignments_unset(alignments * table, u64 key){
  alignments_remove(table, &key, 1);
}

bool alignments_try_get(alignments * table, u64 * id, alignment * horizontal, alignment * vertical){
  void * array[] = {(void* )id, (void* )horizontal, (void* )vertical};
  void * column_pointers[] = {(void *)table->id, (void *)table->horizontal, (void *)table->vertical};
  size_t __index = 0;
  icy_table_finds((icy_table *) table, array[0], &__index, 1);
  if(__index == 0) return false;
  unsigned int sizes[] = {sizeof(u64), sizeof(alignment), sizeof(alignment)};
  for(int i = 1; i < 3; i++){
    if(array[i] != NULL)
      memcpy(array[i], column_pointers[i] + __index * sizes[i], sizes[i]); 
  }
  return true;
}

void alignments_print(alignments * table){
  icy_table_print((icy_table *) table);
}

size_t alignments_iter(alignments * table, u64 * keys, size_t keycnt, u64 * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator){
  return icy_table_iter((icy_table *) table, keys, keycnt, optional_keys_out, indexes, cnt, iterator);

}
