// This file is auto generated by icy-table.
#include "icydb.h"
typedef struct _margin_table{
  char ** column_names;
  char ** column_types;
  size_t count;
  const bool is_multi_table;
  const int column_count;
  int (*cmp) (const u64 * k1, const u64 * k2);
  const size_t sizes[5];

  u64 * key;
  f32 * left;
  f32 * right;
  f32 * up;
  f32 * down;
  icy_mem * key_area;
  icy_mem * left_area;
  icy_mem * right_area;
  icy_mem * up_area;
  icy_mem * down_area;
}margin_table;

margin_table * margin_table_create(const char * optional_name);
void margin_table_set(margin_table * table, u64 key, f32 left, f32 right, f32 up, f32 down);
void margin_table_insert(margin_table * table, u64 * key, f32 * left, f32 * right, f32 * up, f32 * down, size_t count);
void margin_table_lookup(margin_table * table, u64 * keys, size_t * out_indexes, size_t count);
void margin_table_remove(margin_table * table, u64 * keys, size_t key_count);
void margin_table_clear(margin_table * table);
void margin_table_unset(margin_table * table, u64 key);
bool margin_table_try_get(margin_table * table, u64 * key, f32 * left, f32 * right, f32 * up, f32 * down);
void margin_table_print(margin_table * table);
size_t margin_table_iter(margin_table * table, u64 * keys, size_t keycnt, u64 * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator);
