// This file is auto generated by icy-table.
#ifndef TABLE_COMPILER_INDEX
#define TABLE_COMPILER_INDEX
#define array_element_size(array) sizeof(array[0])
#define array_count(array) (sizeof(array)/array_element_size(array))
#include "icydb.h"
#include <stdlib.h>
#endif


margin_table * margin_table_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"key", (char *)"left", (char *)"right", (char *)"up", (char *)"down"};
  static const char * const column_types[] = {"u64", "f32", "f32", "f32", "f32"};
  margin_table * instance = calloc(sizeof(margin_table), 1);
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  
  icy_table_init((icy_table * )instance, optional_name, 5, (unsigned int[]){sizeof(u64), sizeof(f32), sizeof(f32), sizeof(f32), sizeof(f32)}, (char *[]){(char *)"key", (char *)"left", (char *)"right", (char *)"up", (char *)"down"});
  
  return instance;
}

void margin_table_insert(margin_table * table, u64 * key, f32 * left, f32 * right, f32 * up, f32 * down, size_t count){
  void * array[] = {(void* )key, (void* )left, (void* )right, (void* )up, (void* )down};
  icy_table_inserts((icy_table *) table, array, count);
}

void margin_table_set(margin_table * table, u64 key, f32 left, f32 right, f32 up, f32 down){
  void * array[] = {(void* )&key, (void* )&left, (void* )&right, (void* )&up, (void* )&down};
  icy_table_inserts((icy_table *) table, array, 1);
}

void margin_table_lookup(margin_table * table, u64 * keys, size_t * out_indexes, size_t count){
  icy_table_finds((icy_table *) table, keys, out_indexes, count);
}

void margin_table_remove(margin_table * table, u64 * keys, size_t key_count){
  size_t indexes[key_count];
  size_t index = 0;
  size_t cnt = 0;
  while(0 < (cnt = icy_table_iter((icy_table *) table, keys, key_count, NULL, indexes, array_count(indexes), &index))){
    icy_table_remove_indexes((icy_table *) table, indexes, cnt);
    index = 0;
  }
}

void margin_table_clear(margin_table * table){
  icy_table_clear((icy_table *) table);
}

void margin_table_unset(margin_table * table, u64 key){
  margin_table_remove(table, &key, 1);
}

bool margin_table_try_get(margin_table * table, u64 * key, f32 * left, f32 * right, f32 * up, f32 * down){
  void * array[] = {(void* )key, (void* )left, (void* )right, (void* )up, (void* )down};
  void * column_pointers[] = {(void *)table->key, (void *)table->left, (void *)table->right, (void *)table->up, (void *)table->down};
  size_t __index = 0;
  icy_table_finds((icy_table *) table, array[0], &__index, 1);
  if(__index == 0) return false;
  unsigned int sizes[] = {sizeof(u64), sizeof(f32), sizeof(f32), sizeof(f32), sizeof(f32)};
  for(int i = 1; i < 5; i++){
    if(array[i] != NULL)
      memcpy(array[i], column_pointers[i] + __index * sizes[i], sizes[i]); 
  }
  return true;
}

void margin_table_print(margin_table * table){
  icy_table_print((icy_table *) table);
}

size_t margin_table_iter(margin_table * table, u64 * keys, size_t keycnt, u64 * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator){
  return icy_table_iter((icy_table *) table, keys, keycnt, optional_keys_out, indexes, cnt, iterator);

}
