// This file is auto generated by icy-table.
#include "icydb.h"
typedef struct _redirection_table{
  char ** column_names;
  char ** column_types;
  size_t count;
  const bool is_multi_table;
  const int column_count;
  int (*cmp) (const u64 * k1, const u64 * k2);
  const size_t sizes[3];

  u64 * key;
  u8 * index;
  u64 * redirection;
  icy_mem * key_area;
  icy_mem * index_area;
  icy_mem * redirection_area;
}redirection_table;

redirection_table * redirection_table_create(const char * optional_name);
void redirection_table_set(redirection_table * table, u64 key, u8 index, u64 redirection);
void redirection_table_insert(redirection_table * table, u64 * key, u8 * index, u64 * redirection, size_t count);
void redirection_table_lookup(redirection_table * table, u64 * keys, size_t * out_indexes, size_t count);
void redirection_table_remove(redirection_table * table, u64 * keys, size_t key_count);
void redirection_table_clear(redirection_table * table);
void redirection_table_unset(redirection_table * table, u64 key);
bool redirection_table_try_get(redirection_table * table, u64 * key, u8 * index, u64 * redirection);
void redirection_table_print(redirection_table * table);
size_t redirection_table_iter(redirection_table * table, u64 * keys, size_t keycnt, u64 * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator);
